/**
 * academyStrings.js — testi dell'interfaccia Academy (IT/EN).
 * I contenuti delle lezioni sono bilingui nei dati; queste sono solo le scritte fisse.
 */
export const STRINGS = {
  it: {
    brand: 'Academy', backToApp: '← App', workspace: 'Workspace',
    hubTitle: 'Impara la finanza giocando',
    hubSub: 'Lezioni brevi e interattive. Capisci i concetti, poi applicali sul sentiment reale di Cheruvo.',
    paths: 'Percorsi', leaderboard: 'Classifica',
    howXp: 'Come guadagni XP',
    xpComplete: '+50 XP · lezione completata',
    xpCorrect: '+20 XP · risposta corretta',
    optIn: 'Su iscrizione · puoi usare un nickname',
    start: 'Inizia', review: 'Rivedi', done: 'Completato', comingSoon: 'In arrivo',
    backToHub: '← Percorsi', question: 'Domanda', next: 'Avanti', finish: 'Concludi',
    correct: 'Giusto!', wrong: 'Non proprio', lessonDone: 'Lezione completata!',
    xpEarned: 'XP guadagnati', restart: 'Ricomincia', backToPaths: 'Torna ai percorsi',
    empty: 'Nessun contenuto ancora. Torna presto!', loading: 'Caricamento…',
    // workspace
    newLesson: 'Nuova lezione', backToList: '← Lezioni', title: 'Titolo',
    options: 'Opzioni (seleziona la corretta)', explanation: 'Spiegazione',
    addQuestion: '+ Aggiungi domanda', removeQ: 'Rimuovi', publish: 'Pubblica',
    saveDraft: 'Salva bozza', preview: 'Anteprima live', genAI: '✨ Genera con AI',
    aiTopic: 'Argomento (es. ETF per principianti)', draft: 'bozza', live: 'live',
    edit: 'Modifica', del: 'Elimina', confirmDel: 'Eliminare questa lezione?',
    saved: 'Salvato', noAdmin: 'Accesso riservato agli amministratori.',
    settings: 'Impostazioni', lessonsTab: 'Lezioni',
    yourProfile: 'Il tuo profilo', nickname: 'Nickname (mostrato in classifica)',
    joinLeaderboard: 'Partecipa alla classifica', save: 'Salva',
    adminsTitle: 'Amministratori',
    adminsHelp: 'Gli admin possono creare/modificare le lezioni e gestire gli altri admin.',
    addByEmail: "Email dell'utente da promuovere", makeAdmin: 'Rendi admin',
    you: '(tu)', remove: 'Rimuovi',
    chooseType: 'Scegli il tipo di gioco', continue: 'Continua', cardsLeft: 'rimaste',
    flip: 'Tocca per girare', knew: 'La sapevo', again: 'Da rivedere',
    simModel: 'Modello', teachText: 'Spiegazione "in parole povere"',
    term: 'Termine', definition: 'Definizione', example: 'Esempio', addCard: '+ Aggiungi carta',
    scene: 'Scena', startScene: 'inizio', sceneText: 'Testo della scena', scnTicker: 'Titolo collegato (opz.)',
    choiceLabel: 'Scelta', feedback: 'Feedback', goesTo: 'Va a', theEnd: 'Fine', addChoice: '+ Scelta', addNode: '+ Aggiungi scena',
    level: 'Livello', levelBase: 'Base', levelInter: 'Intermedio', levelAdv: 'Avanzato',
    classes: 'Classi', classesTitle: 'Le tue classi', createClass: 'Crea classe', className: 'Nome della classe',
    joinClass: 'Unisciti', joinCode: 'Codice classe', membersLabel: 'membri', noClasses: 'Nessuna classe ancora.',
    roleLabel: 'Ruolo', roleStudent: 'Studente', roleTeacher: 'Docente',
    chooseRole: 'Come vuoi usare l\'Academy?', chooseRoleSub: 'Puoi cambiarlo quando vuoi dalle impostazioni.',
    stream: 'Bacheca', membersTab: 'Membri', chat: 'Chat', shareCode: 'Codice d\'invito', leave: 'Esci dalla classe',
    confirmLeave: 'Uscire da questa classe?', post: 'Pubblica', announcement: 'Annuncio', material: 'Materiale/link',
    assignLesson: 'Assegna lezione', uploadFile: 'Carica file', writeHere: 'Scrivi qui...', linkUrl: 'Link (URL)',
    openLesson: 'Apri la lezione', writeMsg: 'Scrivi un messaggio...', send: 'Invia', copy: 'Copia',
    // Lezioni dal Libro (wizard docente)
    bookChip: 'Dal libro', bkTitle: 'Lezioni dal libro',
    bkIntro: 'Carica un capitolo del tuo libro (PDF o foto): ricevi bozze di lezione pronte da rivedere e assegnare.',
    bkUploadPdf: 'Carica un PDF', bkUploadPdfSub: 'il libro o un capitolo · max 25 MB',
    bkUploadPhotos: 'Scatta o scegli foto delle pagine', bkUploadPhotosSub: 'fino a 20 foto, in ordine di lettura',
    bkPrivacy: '🔒 Il tuo file resta privato: lo leggiamo per creare le lezioni e poi lo eliminiamo. Le lezioni riformulano i concetti, non copiano il testo.',
    bkContinue: 'Continua →', bkBack: '← Indietro', bkCancel: 'Annulla',
    bkTocTitle: 'Ecco cosa ho trovato', bkTocSub: 'Spunta i capitoli che ti interessano. Puoi correggere i titoli.',
    bkPages: 'pagg.', bkChaptersFound: 'capitoli rilevati',
    bkConfigTitle: 'Come le vuoi?', bkPerChapter: 'Lezioni per capitolo', bkDifficulty: 'Difficoltà',
    bkMixed: 'Mista', bkMixedHint: '«Mista» crea lezioni su più livelli, utile per classi eterogenee.',
    bkTypes: 'Tipi di lezione', bkGenerate: '✨ Genera le lezioni',
    bkSummary1: 'lezioni', bkSummary2: 'pronte in circa un minuto',
    bkWorkingExtract: 'Sto leggendo il tuo materiale…', bkWorkingGen: 'Sto creando le tue lezioni…',
    bkWait: 'Puoi restare qui: di solito ci vuole meno di un minuto.',
    bkReviewTitle: 'Le tue bozze sono pronte', bkReviewSub: 'Provale, modificale o rigenerale. Niente arriva agli studenti senza il tuo ok.',
    bkRegen: '↻ Rigenera', bkRegenNote: 'Cosa devo cambiare? (es. "più facile", "più esempi pratici")',
    bkAssignTitle: 'A chi le assegni?', bkAssignSub: 'Le lezioni vengono pubblicate e arrivano in bacheca.',
    bkDue: 'Consegna (facoltativa, es. "20 luglio")', bkNoteOpt: 'Nota per la classe (facoltativa)',
    bkAssign: '✓ Pubblica e assegna', bkSkipAssign: 'Salva come bozze e chiudi',
    bkDoneTitle: 'Fatto!', bkDoneSub: 'Lezioni pubblicate e assegnate alla classe.',
    bkOpenClass: 'Apri la classe', bkNewRun: 'Genera da un altro capitolo',
    bkNoClasses: 'Non hai ancora classi: creane una dalla sezione Classi.',
    bkErr: 'Qualcosa è andato storto', bkRetry: 'Riprova',
  },
  en: {
    brand: 'Academy', backToApp: '← App', workspace: 'Workspace',
    hubTitle: 'Learn finance by playing',
    hubSub: 'Short, interactive lessons. Grasp the concepts, then apply them to Cheruvo\'s real sentiment.',
    paths: 'Paths', leaderboard: 'Leaderboard',
    howXp: 'How you earn XP',
    xpComplete: '+50 XP · lesson completed',
    xpCorrect: '+20 XP · correct answer',
    optIn: 'Opt-in · you can use a nickname',
    start: 'Start', review: 'Review', done: 'Completed', comingSoon: 'Coming soon',
    backToHub: '← Paths', question: 'Question', next: 'Next', finish: 'Finish',
    correct: 'Correct!', wrong: 'Not quite', lessonDone: 'Lesson complete!',
    xpEarned: 'XP earned', restart: 'Restart', backToPaths: 'Back to paths',
    empty: 'No content yet. Check back soon!', loading: 'Loading…',
    newLesson: 'New lesson', backToList: '← Lessons', title: 'Title',
    options: 'Options (pick the correct one)', explanation: 'Explanation',
    addQuestion: '+ Add question', removeQ: 'Remove', publish: 'Publish',
    saveDraft: 'Save draft', preview: 'Live preview', genAI: '✨ Generate with AI',
    aiTopic: 'Topic (e.g. ETFs for beginners)', draft: 'draft', live: 'live',
    edit: 'Edit', del: 'Delete', confirmDel: 'Delete this lesson?',
    saved: 'Saved', noAdmin: 'Admins only.',
    settings: 'Settings', lessonsTab: 'Lessons',
    yourProfile: 'Your profile', nickname: 'Nickname (shown on the leaderboard)',
    joinLeaderboard: 'Join the leaderboard', save: 'Save',
    adminsTitle: 'Administrators',
    adminsHelp: 'Admins can create/edit lessons and manage other admins.',
    addByEmail: 'Email of the user to promote', makeAdmin: 'Make admin',
    you: '(you)', remove: 'Remove',
    chooseType: 'Choose a game type', continue: 'Continue', cardsLeft: 'left',
    flip: 'Tap to flip', knew: 'I knew it', again: 'Review again',
    simModel: 'Model', teachText: 'Plain-language explanation',
    term: 'Term', definition: 'Definition', example: 'Example', addCard: '+ Add card',
    scene: 'Scene', startScene: 'start', sceneText: 'Scene text', scnTicker: 'Linked ticker (opt.)',
    choiceLabel: 'Choice', feedback: 'Feedback', goesTo: 'Goes to', theEnd: 'The end', addChoice: '+ Choice', addNode: '+ Add scene',
    level: 'Level', levelBase: 'Beginner', levelInter: 'Intermediate', levelAdv: 'Advanced',
    classes: 'Classes', classesTitle: 'Your classes', createClass: 'Create class', className: 'Class name',
    joinClass: 'Join', joinCode: 'Class code', membersLabel: 'members', noClasses: 'No classes yet.',
    roleLabel: 'Role', roleStudent: 'Student', roleTeacher: 'Teacher',
    chooseRole: 'How will you use the Academy?', chooseRoleSub: 'You can change this anytime in settings.',
    stream: 'Stream', membersTab: 'Members', chat: 'Chat', shareCode: 'Invite code', leave: 'Leave class',
    confirmLeave: 'Leave this class?', post: 'Post', announcement: 'Announcement', material: 'Material/link',
    assignLesson: 'Assign lesson', uploadFile: 'Upload file', writeHere: 'Write here...', linkUrl: 'Link (URL)',
    openLesson: 'Open lesson', writeMsg: 'Write a message...', send: 'Send', copy: 'Copy',
    // Lessons from the Book (teacher wizard)
    bookChip: 'From the book', bkTitle: 'Lessons from the book',
    bkIntro: 'Upload a chapter of your textbook (PDF or photos): get lesson drafts ready to review and assign.',
    bkUploadPdf: 'Upload a PDF', bkUploadPdfSub: 'the book or one chapter · max 25 MB',
    bkUploadPhotos: 'Take or pick photos of the pages', bkUploadPhotosSub: 'up to 20 photos, in reading order',
    bkPrivacy: '🔒 Your file stays private: we read it to create the lessons, then delete it. Lessons rephrase concepts, they never copy the text.',
    bkContinue: 'Continue →', bkBack: '← Back', bkCancel: 'Cancel',
    bkTocTitle: 'Here is what I found', bkTocSub: 'Tick the chapters you care about. You can fix the titles.',
    bkPages: 'pp.', bkChaptersFound: 'chapters detected',
    bkConfigTitle: 'How do you want them?', bkPerChapter: 'Lessons per chapter', bkDifficulty: 'Difficulty',
    bkMixed: 'Mixed', bkMixedHint: '"Mixed" creates lessons at multiple levels, great for diverse classes.',
    bkTypes: 'Lesson types', bkGenerate: '✨ Generate lessons',
    bkSummary1: 'lessons', bkSummary2: 'ready in about a minute',
    bkWorkingExtract: 'Reading your material…', bkWorkingGen: 'Creating your lessons…',
    bkWait: 'You can stay here: it usually takes less than a minute.',
    bkReviewTitle: 'Your drafts are ready', bkReviewSub: 'Try them, edit or regenerate. Nothing reaches students without your OK.',
    bkRegen: '↻ Regenerate', bkRegenNote: 'What should I change? (e.g. "easier", "more practical examples")',
    bkAssignTitle: 'Who gets them?', bkAssignSub: 'Lessons get published and appear in the class stream.',
    bkDue: 'Due date (optional, e.g. "July 20")', bkNoteOpt: 'Note for the class (optional)',
    bkAssign: '✓ Publish & assign', bkSkipAssign: 'Save as drafts and close',
    bkDoneTitle: 'Done!', bkDoneSub: 'Lessons published and assigned to the class.',
    bkOpenClass: 'Open the class', bkNewRun: 'Generate from another chapter',
    bkNoClasses: 'No classes yet: create one from the Classes section.',
    bkErr: 'Something went wrong', bkRetry: 'Retry',
  },
}

export const pick = (loc, lang) => (loc && (loc[lang] || loc.it || loc.en)) || ''
