/**
 * academyStrings.js — testi dell'interfaccia Academy (IT/EN).
 * I contenuti delle lezioni sono bilingui nei dati; queste sono solo le scritte fisse.
 */
export const STRINGS = {
  it: {
    brand: 'Academy', backToApp: '← App', workspace: 'Workspace',
    hubTitle: 'Impara la finanza giocando',
    hubSub: 'Lezioni brevi e interattive. Capisci i concetti, poi applicali sul sentiment reale di Cheruvo.',
    paths: 'Percorsi', leaderboard: 'Classifica',
    howXp: 'Come guadagni XP',
    xpComplete: '+50 XP · lezione completata',
    xpCorrect: '+20 XP · risposta corretta',
    optIn: 'Su iscrizione · puoi usare un nickname',
    start: 'Inizia', review: 'Rivedi', done: 'Completato', comingSoon: 'In arrivo',
    backToHub: '← Percorsi', question: 'Domanda', next: 'Avanti', finish: 'Concludi',
    correct: 'Giusto!', wrong: 'Non proprio', lessonDone: 'Lezione completata!',
    xpEarned: 'XP guadagnati', restart: 'Ricomincia', backToPaths: 'Torna ai percorsi',
    empty: 'Nessun contenuto ancora. Torna presto!', loading: 'Caricamento…',
    // workspace
    newLesson: 'Nuova lezione', backToList: '← Lezioni', title: 'Titolo',
    options: 'Opzioni (seleziona la corretta)', explanation: 'Spiegazione',
    addQuestion: '+ Aggiungi domanda', removeQ: 'Rimuovi', publish: 'Pubblica',
    saveDraft: 'Salva bozza', preview: 'Anteprima live', genAI: '✨ Genera con AI',
    aiTopic: 'Argomento (es. ETF per principianti)', draft: 'bozza', live: 'live',
    edit: 'Modifica', del: 'Elimina', confirmDel: 'Eliminare questa lezione?',
    saved: 'Salvato', noAdmin: 'Accesso riservato agli amministratori.',
    settings: 'Impostazioni', lessonsTab: 'Lezioni',
    yourProfile: 'Il tuo profilo', nickname: 'Nickname (mostrato in classifica)',
    joinLeaderboard: 'Partecipa alla classifica', save: 'Salva',
    adminsTitle: 'Amministratori',
    adminsHelp: 'Gli admin possono creare/modificare le lezioni e gestire gli altri admin.',
    addByEmail: "Email dell'utente da promuovere", makeAdmin: 'Rendi admin',
    you: '(tu)', remove: 'Rimuovi',
    chooseType: 'Scegli il tipo di gioco', continue: 'Continua', cardsLeft: 'rimaste',
    flip: 'Tocca per girare', knew: 'La sapevo', again: 'Da rivedere',
    simModel: 'Modello', teachText: 'Spiegazione "in parole povere"',
    term: 'Termine', definition: 'Definizione', example: 'Esempio', addCard: '+ Aggiungi carta',
    scene: 'Scena', startScene: 'inizio', sceneText: 'Testo della scena', scnTicker: 'Titolo collegato (opz.)',
    choiceLabel: 'Scelta', feedback: 'Feedback', goesTo: 'Va a', theEnd: 'Fine', addChoice: '+ Scelta', addNode: '+ Aggiungi scena',
  },
  en: {
    brand: 'Academy', backToApp: '← App', workspace: 'Workspace',
    hubTitle: 'Learn finance by playing',
    hubSub: 'Short, interactive lessons. Grasp the concepts, then apply them to Cheruvo\'s real sentiment.',
    paths: 'Paths', leaderboard: 'Leaderboard',
    howXp: 'How you earn XP',
    xpComplete: '+50 XP · lesson completed',
    xpCorrect: '+20 XP · correct answer',
    optIn: 'Opt-in · you can use a nickname',
    start: 'Start', review: 'Review', done: 'Completed', comingSoon: 'Coming soon',
    backToHub: '← Paths', question: 'Question', next: 'Next', finish: 'Finish',
    correct: 'Correct!', wrong: 'Not quite', lessonDone: 'Lesson complete!',
    xpEarned: 'XP earned', restart: 'Restart', backToPaths: 'Back to paths',
    empty: 'No content yet. Check back soon!', loading: 'Loading…',
    newLesson: 'New lesson', backToList: '← Lessons', title: 'Title',
    options: 'Options (pick the correct one)', explanation: 'Explanation',
    addQuestion: '+ Add question', removeQ: 'Remove', publish: 'Publish',
    saveDraft: 'Save draft', preview: 'Live preview', genAI: '✨ Generate with AI',
    aiTopic: 'Topic (e.g. ETFs for beginners)', draft: 'draft', live: 'live',
    edit: 'Edit', del: 'Delete', confirmDel: 'Delete this lesson?',
    saved: 'Saved', noAdmin: 'Admins only.',
    settings: 'Settings', lessonsTab: 'Lessons',
    yourProfile: 'Your profile', nickname: 'Nickname (shown on the leaderboard)',
    joinLeaderboard: 'Join the leaderboard', save: 'Save',
    adminsTitle: 'Administrators',
    adminsHelp: 'Admins can create/edit lessons and manage other admins.',
    addByEmail: 'Email of the user to promote', makeAdmin: 'Make admin',
    you: '(you)', remove: 'Remove',
    chooseType: 'Choose a game type', continue: 'Continue', cardsLeft: 'left',
    flip: 'Tap to flip', knew: 'I knew it', again: 'Review again',
    simModel: 'Model', teachText: 'Plain-language explanation',
    term: 'Term', definition: 'Definition', example: 'Example', addCard: '+ Add card',
    scene: 'Scene', startScene: 'start', sceneText: 'Scene text', scnTicker: 'Linked ticker (opt.)',
    choiceLabel: 'Choice', feedback: 'Feedback', goesTo: 'Goes to', theEnd: 'The end', addChoice: '+ Choice', addNode: '+ Add scene',
  },
}

export const pick = (loc, lang) => (loc && (loc[lang] || loc.it || loc.en)) || ''
